apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  labels:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      name: db-migrate
    spec:
      {{- $pullSecrets := index .Values "imagePullSecrets" -}}
      {{- with $pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ index .Values "image" "repository" }}:{{ index .Values "image" "tag" | default .Chart.AppVersion }}"
        imagePullPolicy: {{ index .Values "image" "pullPolicy" }}
        command: ["dotnet"]
        args: ["DeepSpace.Identity.dll", "/seed"]
        {{- with .Values.env }}
        env:
        {{- range $k, $v := . }}
          - name: {{ $k | quote }}
            value: {{ $v | quote }}
        {{- end }}
        {{- end }}
        {{- with .Values.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      restartPolicy: Never
