apiVersion: batch/v1
kind: Job
metadata:
  name: deepspace-db-migrate
  labels:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      name: deepspace-db-migrate
    spec:
      {{- with (concat (.Values.cli.imagePullSecrets | default list) (.Values.global.imagePullSecrets | default list)) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.cli.image.repository }}:{{ .Values.cli.image.tag | default .Values.global.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.cli.image.pullPolicy | default .Values.global.image.pullPolicy }}
        command: ["dotnet"]
        args: ["DeepSpace.CommandLine.dll", "migrate"]
        {{- with (merge (.Values.cli.env | default dict) (.Values.global.env | default dict)) }}
        env:
        {{- range $k, $v := . }}
          - name: {{ $k | quote }}
            value: {{ $v | quote }}
        {{- end }}
        {{- end }}
        {{- with (concat (.Values.cli.envFrom | default list) (.Values.global.envFrom | default list)) }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      restartPolicy: Never
