global:
  env: {}
  image:
    tag: ""
    pullPolicy: IfNotPresent
  imagePullSecrets: []

cli:
  image:
    repository: ghcr.io/tgardner/ogame-cli
    pullPolicy: ""
    tag: ""
  env: {}
  envFrom: []
