global:
  env: {}
  image:
    tag: ""
    pullPolicy: IfNotPresent
  imagePullSecrets: []

cli:
  nameOverride: cli
  image:
    repository: ghcr.io/tgardner/ogame-cli
    pullPolicy: ""
    tag: ""
  env: {}
  envFrom: []
  args:
  - DeepSpace.CommandLine.dll
  - migrate
